apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if .Values.mongodb.enabled }}
  mongodb-url: {{ include "auth-service.mongodbUrl" . | b64enc | quote }}
  {{- else if .Values.secrets.mongodbUrl }}
  mongodb-url: {{ .Values.secrets.mongodbUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ include "auth-service.redisUrl" . | b64enc | quote }}
  {{- else if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  postgresql-url: {{ include "auth-service.postgresqlUrl" . | b64enc | quote }}
  {{- else if .Values.secrets.postgresqlUrl }}
  postgresql-url: {{ .Values.secrets.postgresqlUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.brevoApiKey }}
  brevo-api-key: {{ .Values.secrets.brevoApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.sendgridApiKey }}
  sendgrid-api-key: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}
  {{- end }}