# cargo-deny configuration for enhanced security and dependency management

[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

# The advisories section configures handling of security advisories
[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    "RUSTSEC-2023-0071",  # RSA timing attack - acceptable risk for our use case
]

# The licenses section configures licensing requirements
[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "either"
default = "deny"
confidence-threshold = 0.8

# The bans section configures specific crates/versions that are banned
[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = [
    { name = "openssl", version = "< 0.10.60" },
    { name = "tokio", version = "< 1.35.0" },
    { name = "serde", version = "< 1.0.190" },
    { name = "reqwest", version = "< 0.11.22" },
]
skip = [
    { name = "proc-macro2" },
    { name = "syn" },
    { name = "quote" },
]
skip-tree = [
    { name = "windows-sys" },
]

# The sources section configures which sources are allowed
[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []