version: '3.8'

services:
  # MongoDB for development
  mongodb:
    image: mongo:7
    container_name: rust-auth-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: auth_service_dev
    ports:
      - "27018:27017"
    volumes:
      - mongodb_dev_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # PostgreSQL for development
  postgresql:
    image: postgres:15
    container_name: rust-auth-postgresql-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: auth_service_dev
    ports:
      - "5433:5432"
    volumes:
      - postgresql_dev_data:/var/lib/postgresql/data
      - ./migrations/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # MySQL for development
  mysql:
    image: mysql:8.0
    container_name: rust-auth-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: auth_service_dev
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./migrations/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: rust-auth-redis-dev
    command: redis-server --requirepass password123
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: rust-auth-mailhog-dev
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Development service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: rust-auth-service-dev
    depends_on:
      mongodb:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    environment:
      # Development configurations for different databases
      MONGODB_DEV_URL: "mongodb://admin:password123@mongodb:27017/auth_service_dev?authSource=admin"
      POSTGRESQL_DEV_URL: "postgresql://postgres:password123@postgresql:5432/auth_service_dev"
      MYSQL_DEV_URL: "mysql://root:password123@mysql:3306/auth_service_dev"
      REDIS_DEV_URL: "redis://:password123@redis:6379"
      SMTP_DEV_HOST: "mailhog"
      SMTP_DEV_PORT: "1025"
      JWT_SECRET: "dev-secret-key-change-in-production"
      RUST_LOG: "info"
      RUST_BACKTRACE: "1"
    volumes:
      - .:/app
      - /app/target  # Anonymous volume for target directory
    working_dir: /app
    command: ["cargo", "test", "--", "--test-threads=1"]
    networks:
      - auth-dev-network

  # Performance testing with different databases
  performance-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: rust-auth-performance-dev
    depends_on:
      - auth-service
    environment:
      MONGODB_DEV_URL: "mongodb://admin:password123@mongodb:27017/auth_service_dev?authSource=admin"
      POSTGRESQL_DEV_URL: "postgresql://postgres:password123@postgresql:5432/auth_service_dev"
      MYSQL_DEV_URL: "mysql://root:password123@mysql:3306/auth_service_dev"
      REDIS_DEV_URL: "redis://:password123@redis:6379"
      JWT_SECRET: "dev-secret-key-for-performance-tests"
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    command: ["cargo", "test", "--release", "--", "--test-threads=1", "performance"]
    networks:
      - auth-dev-network

volumes:
  mongodb_dev_data:
  postgresql_dev_data:
  mysql_dev_data:
  redis_dev_data:

networks:
  auth-dev-network:
    driver: bridge