apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
  labels:
    name: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: authentication-platform
    app.kubernetes.io/version: "1.0.0"
  annotations:
    description: "High-performance Rust Authentication Service namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: auth-service-quota
  namespace: auth-service
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: auth-service-limits
  namespace: auth-service
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim