name: Basic CI

on:
  push:
    branches: [ main, milestone-4-advanced-auth ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  basic-checks:
    name: Basic Compilation Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Check code formatting
      run: cargo fmt --all -- --check
      
    - name: Basic compilation check
      run: cargo check
      
    - name: Run basic tests
      run: cargo test --lib